/* Si vuole creare un gestionale per il cinema "MovieStars" con le seguenti caratteristiche: 

- Vogliamo memorizzare una anagrafica delle sale presenti nel cinema indicando
	+ posti, 
	+ nome
	+ città di appartenenza

- Nell'arco di una giornata, una sala può ospitare più film e un film può essere proiettato all'interno della stessa sala in momenti diversi della giornata

- Per ogni film proiettato nelle sale vogliamo gestire le seguenti informazioni: 
	+ Titolo, Anno di produzione, nazionalità, regista e il genere. 

- Per ogni film, vogliamo gestire informazioni relative agli attori: 
	+ Nome, Anno di nascita e nazionalità  */
  
 CREATE DATABASE moviestars
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Italian_Italy.1252'
    LC_CTYPE = 'Italian_Italy.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
    
CREATE TABLE IF NOT EXISTS public.film
(
    codice integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    titolo character varying(25) COLLATE pg_catalog."default" NOT NULL,
    genere character varying(25) COLLATE pg_catalog."default" NOT NULL,
    anno_produzione date NOT NULL,
    "nazionalità" character varying(25) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT film_pkey PRIMARY KEY (codice)
)

CREATE TABLE IF NOT EXISTS public.artista
(
    codice_fiscale character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nome character varying(25) COLLATE pg_catalog."default" NOT NULL,
    cognome character varying(25) COLLATE pg_catalog."default" NOT NULL,
    "nazionalità" character varying(25) COLLATE pg_catalog."default" NOT NULL,
    anno_nascita date NOT NULL,
    tipo character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT artista_pkey PRIMARY KEY (codice_fiscale)
)

CREATE TABLE IF NOT EXISTS public.cinema
(
    codice integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nome character varying(25) COLLATE pg_catalog."default" NOT NULL,
    "città" character varying(25) COLLATE pg_catalog."default" NOT NULL,
    numero_sale integer,
    CONSTRAINT cinema_pkey PRIMARY KEY (codice)
)

CREATE TABLE IF NOT EXISTS public.sala
(
    codice_cinema integer NOT NULL,
    numero_sala smallint NOT NULL,
    numero_posti integer,
    CONSTRAINT sala_pkey PRIMARY KEY (codice_cinema, numero_sala),
    CONSTRAINT fk_cinema FOREIGN KEY (codice_cinema)
        REFERENCES public.cinema (codice) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

CREATE TABLE IF NOT EXISTS public.spettacolo
(
    codice_cinema integer NOT NULL,
    numero_sala smallint NOT NULL,
    codice_film integer NOT NULL,
    orario time without time zone NOT NULL,
    data date NOT NULL,
    CONSTRAINT spettacolo_pkey PRIMARY KEY (codice_cinema, numero_sala, codice_film, orario, data),
    CONSTRAINT fk_film FOREIGN KEY (codice_film)
        REFERENCES public.film (codice) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_sala_cinema FOREIGN KEY (codice_cinema, numero_sala)
        REFERENCES public.sala (codice_cinema, numero) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
    
